name: the_cholera_files
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  syncfusion_flutter_maps: ^21.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/home.svg
    - assets/icons/notifications.svg
    - assets/icons/search.svg
    - assets/icons/menu.svg
    - assets/icons/user.svg
    - assets/icons/signs_symptoms.svg
    - assets/icons/prevention.svg
    - assets/icons/call.svg
    - assets/icons/reports.svg
    - assets/icons/risk_zones.svg
    - assets/icons/calendar.svg

    #map data
    - assets/maps/malawi.json
    - assets/maps/australia.json
